"""
Extracted from LLM Training Methodology.
Auto-generated by extract_code_from_methodology.py
"""

import json

import numpy as np

def calculate_latency_percentiles(model_name, log_path="ab_test_logs.jsonl"):
    """Calculate latency percentiles for a model."""

    with open(log_path, "r") as f:
        all_logs = [json.loads(line) for line in f]
    logs = [log for log in all_logs if log["model"] == model_name]

    latencies = [log["latency_ms"] for log in logs if log["error"] is None]

    p50 = np.percentile(latencies, 50)
    p95 = np.percentile(latencies, 95)
    p99 = np.percentile(latencies, 99)

    print(f"{model_name} Latency:")
    print(f"  p50: {p50:.1f}ms")
    print(f"  p95: {p95:.1f}ms")
    print(f"  p99: {p99:.1f}ms")

    return {"p50": p50, "p95": p95, "p99": p99}
