"""
Extracted from LLM Training Methodology.
Auto-generated by extract_code_from_methodology.py
"""

import logging

from flask import request

logging.basicConfig(
    filename='llm_requests.log',
    level=logging.INFO,
    format='%(asctime)s - %(message)s'
)


def register_routes(app, model):
    """Register a logged chat route on an existing Flask app."""

    @app.route("/v1/chat/completions", methods=["POST"])
    def chat():
        data = request.json
        logging.info(f"Request: {data['messages']}")

        response = model.generate(data["messages"])

        logging.info(f"Response: {response}")
        return response

    return app
