"""
Extracted from LLM Training Methodology.
Auto-generated by extract_code_from_methodology.py
"""

from alerts import send_alert
from ab_testing_server import AB_TEST_CONFIG, metrics

# Below this many requests, Model A's own error rate is too noisy to trust
# as a rollback baseline (e.g. 0 errors out of 3 requests looks like a
# perfect 0% baseline but tells you nothing).
MIN_BASELINE_REQUESTS = 50

# Minimum absolute error-rate gap required to trigger rollback, in addition
# to the 2x relative check below.
MIN_ABSOLUTE_GAP = 0.05


def check_health_and_rollback(metrics=metrics, ab_test_config=AB_TEST_CONFIG):
    """Automatically rollback if Model B performs poorly."""

    if metrics["model_b"]["requests"] < 50:
        return  # Not enough data yet

    if metrics["model_a"]["requests"] < MIN_BASELINE_REQUESTS:
        return  # Model A baseline itself too small to be a reliable comparison

    error_rate_a = metrics["model_a"]["errors"] / metrics["model_a"]["requests"]
    error_rate_b = metrics["model_b"]["errors"] / metrics["model_b"]["requests"]

    # Rollback if Model B error rate is more than 2x Model A's AND at least
    # MIN_ABSOLUTE_GAP worse in absolute terms. The absolute floor matters
    # because when error_rate_a is 0 (a very plausible healthy baseline),
    # `error_rate_b > 2 * 0` is satisfied by a single stray error out of
    # hundreds of requests -- the multiplicative check alone is degenerate
    # against a zero baseline.
    if error_rate_b > 2 * error_rate_a and (error_rate_b - error_rate_a) > MIN_ABSOLUTE_GAP:
        print(f"⚠️ ROLLBACK: Model B error rate too high ({error_rate_b:.1%} vs {error_rate_a:.1%})")
        ab_test_config["model_b_weight"] = 0.0
        ab_test_config["model_a_weight"] = 1.0
        send_alert("Model B rolled back due to high error rate", severity="critical")


def register_periodic_check(schedule_module):
    """Run health check every 5 minutes using the `schedule` package."""
    schedule_module.every(5).minutes.do(check_health_and_rollback)


if __name__ == "__main__":
    import schedule
    register_periodic_check(schedule)
