"""
Extracted from LLM Training Methodology.
Auto-generated by extract_code_from_methodology.py
"""

def check_health_and_rollback():
    """Automatically rollback if Model B performs poorly."""

    if metrics["model_b"]["requests"] < 50:
        return  # Not enough data yet

    error_rate_a = metrics["model_a"]["errors"] / metrics["model_a"]["requests"]
    error_rate_b = metrics["model_b"]["errors"] / metrics["model_b"]["requests"]

    # Rollback if Model B error rate >2x Model A
    if error_rate_b > 2 * error_rate_a:
        print(f"⚠️ ROLLBACK: Model B error rate too high ({error_rate_b:.1%} vs {error_rate_a:.1%})")
        AB_TEST_CONFIG["model_b_weight"] = 0.0
        AB_TEST_CONFIG["model_a_weight"] = 1.0
        send_alert("Model B rolled back due to high error rate")

# Run health check every 5 minutes
import schedule
schedule.every(5).minutes.do(check_health_and_rollback)
