"""
Extracted from LLM Training Methodology.
Auto-generated by extract_code_from_methodology.py
"""

import json
from difflib import SequenceMatcher

from alerts import send_alert, send_to_pagerduty


class ConceptDriftDetector:
    """Detect when model's learned concepts become outdated."""

    def __init__(self, reference_set_path="reference_test_set.json", baseline_accuracy=0.85):
        self.reference_set_path = reference_set_path
        self.reference_set = self._load_reference_set()
        self.baseline_accuracy = baseline_accuracy  # Your accuracy at deployment time
        self.drift_threshold = 0.15  # Alert if accuracy drops >15%

    def _load_reference_set(self):
        """Load gold-standard test set for drift detection."""
        # This is your evaluation benchmark from training
        with open(self.reference_set_path, "r") as f:
            return json.load(f)

    def check_drift_monthly(self, model):
        """Run drift detection monthly on reference set."""

        print("Running concept drift detection...")

        correct = 0
        total = len(self.reference_set)

        for item in self.reference_set:
            response = model.generate(item["question"])

            # Check if answer is correct (fuzzy match)
            if self._is_correct(response, item["correct_answer"]):
                correct += 1

        current_accuracy = correct / total
        accuracy_drop = self.baseline_accuracy - current_accuracy

        print(f"Reference Set Accuracy: {current_accuracy:.1%}")
        print(f"Baseline Accuracy: {self.baseline_accuracy:.1%}")
        print(f"Accuracy Drop: {accuracy_drop:+.1%}")

        if accuracy_drop > self.drift_threshold:
            self._send_drift_alert(current_accuracy, accuracy_drop)
            return True  # Drift detected

        return False  # No drift

    def _is_correct(self, response: str, correct_answer: str) -> bool:
        """Check if response matches correct answer (fuzzy)."""
        similarity = SequenceMatcher(None, response.lower(), correct_answer.lower()).ratio()
        return similarity > 0.8

    def _send_drift_alert(self, current_accuracy, accuracy_drop):
        """Alert that concept drift detected."""
        alert = send_alert(
            f"Model accuracy dropped from {self.baseline_accuracy:.1%} to {current_accuracy:.1%} "
            f"(drop: {accuracy_drop:+.1%}). Retrain model with updated data.",
            severity="critical",
            log_path="drift_alerts.jsonl",
        )
        send_to_pagerduty(alert)


def run_drift_detection(detector, model):
    drift_detected = detector.check_drift_monthly(model)
    if drift_detected:
        print("⚠️ CONCEPT DRIFT DETECTED - Retraining recommended")


def is_first_run_this_month(state_path="last_drift_check.json"):
    """The `schedule` package (used elsewhere in this file's original form)
    has no monthly unit -- its coarsest built-in interval is `.week`. Track
    the last-run month ourselves instead, following the same date-comparison
    approach get_canary_weight.py already uses correctly."""
    import json as _json
    from datetime import date

    today = date.today()
    try:
        with open(state_path, "r") as f:
            last = _json.load(f)
        already_ran = (last.get("year") == today.year and last.get("month") == today.month)
    except FileNotFoundError:
        already_ran = False

    if not already_ran:
        with open(state_path, "w") as f:
            _json.dump({"year": today.year, "month": today.month}, f)

    return not already_ran


if __name__ == "__main__":
    # Wire this up once, at deployment startup, checked e.g. daily via
    # schedule.every().day.at("00:00").do(...):
    #   detector = ConceptDriftDetector()
    #   if is_first_run_this_month():
    #       run_drift_detection(detector, model)
    print(__doc__)
