"""
Extracted from LLM Training Methodology.
Auto-generated by extract_code_from_methodology.py
"""

import json
from typing import List

import numpy as np
import torch
from scipy.spatial.distance import cosine

from alerts import send_alert, send_to_slack


class DataDriftDetector:
    """Detect when input distribution changes."""

    def __init__(self, model, tokenizer, training_sample_path="training_sample.json"):
        self.model = model
        self.tokenizer = tokenizer
        self.training_sample_path = training_sample_path
        self.reference_embeddings = self._compute_reference_embeddings()
        self.drift_threshold = 0.25  # Alert if distance > 0.25

    def _compute_reference_embeddings(self):
        """Compute embeddings for training data distribution."""
        # Sample 1000 examples from training data
        with open(self.training_sample_path, "r") as f:
            training_data = json.load(f)

        embeddings = [self._get_embedding(item["input"]) for item in training_data[:1000]]

        # Average embedding (centroid)
        reference_centroid = np.mean(embeddings, axis=0)

        return {"centroid": reference_centroid, "embeddings": embeddings}

    def _get_embedding(self, text: str):
        """Get embedding for text using model."""
        inputs = self.tokenizer(text, return_tensors="pt", truncation=True, max_length=512)
        with torch.no_grad():
            outputs = self.model(**inputs, output_hidden_states=True)
            # Use last hidden state, mean pooling
            embedding = outputs.hidden_states[-1].mean(dim=1).cpu().numpy()[0]
        return embedding

    def check_drift_weekly(self, recent_queries: List[str]):
        """Check if recent queries have drifted from training distribution."""

        print("Running data drift detection...")

        # Get embeddings for recent queries
        recent_embeddings = [self._get_embedding(q) for q in recent_queries]
        recent_centroid = np.mean(recent_embeddings, axis=0)

        # Calculate distance between centroids (cosine distance)
        distance = cosine(self.reference_embeddings["centroid"], recent_centroid)

        print(f"Data Drift Distance: {distance:.3f}")

        if distance > self.drift_threshold:
            self._send_drift_alert(distance)
            return True

        return False

    def _send_drift_alert(self, distance):
        """Alert that data drift detected."""
        alert = send_alert(
            f"Input distribution has drifted (distance: {distance:.3f}). "
            "Analyze recent queries for new patterns. Consider collecting new training data.",
            severity="warning",
            log_path="drift_alerts.jsonl",
        )
        send_to_slack(alert)


def check_data_drift(detector, requests_log="llm_requests.log"):
    # Get last 500 queries
    with open(requests_log, "r") as f:
        recent_queries = [json.loads(line)["messages"][-1]["content"] for line in f.readlines()[-500:]]

    drift_detected = detector.check_drift_weekly(recent_queries)
    if drift_detected:
        print("⚠️ DATA DRIFT DETECTED - Input distribution has changed")


if __name__ == "__main__":
    # Wire this up once, at deployment startup:
    #   import schedule
    #   detector = DataDriftDetector(model, tokenizer)
    #   schedule.every().monday.at("00:00").do(check_data_drift, detector)
    print(__doc__)
