"""
Extracted from LLM Training Methodology.
Auto-generated by extract_code_from_methodology.py

Integration example for the main AEGIS project (not this tools/ tree) --
run from the project root so `llm_integration` and `agents` are importable,
with LM Studio (or a vLLM server) running at the given base_url.
"""


def main():
    from llm_integration.lmstudio_client import LMStudioClient

    # Point to your deployed model
    client = LMStudioClient(
        base_url="http://localhost:1234/v1",  # or vLLM server
        model_name="firefighter-llama3.1-8b"
    )

    # Use in expert agent
    from agents.expert_agent import ExpertAgent

    firefighter = ExpertAgent(
        name="Pyragos Ioanna Michaelidou",
        role="Fire Tactical Commander",
        expertise="firefighting",
        llm_client=client
    )

    scenario_data = {
        "description": "A wildfire is approaching a mountain village.",
        "location": {"region": "Evia"},
    }
    assessment = firefighter.assess_scenario(scenario_data)
    return assessment


if __name__ == "__main__":
    print(main())
