"""
Extracted from LLM Training Methodology.
Auto-generated by extract_code_from_methodology.py

Requires real LoRA adapter checkpoints at the given paths.
"""

from transformers import AutoModelForCausalLM
from peft import PeftModel


def load_expert_adapters(base_model_name="meta-llama/Meta-Llama-3.1-8B-Instruct"):
    # Load base model once
    base_model = AutoModelForCausalLM.from_pretrained(base_model_name)

    # Load different LoRA adapters
    firefighter_model = PeftModel.from_pretrained(base_model, "./lora/firefighter")
    police_model = PeftModel.from_pretrained(base_model, "./lora/police")
    medical_model = PeftModel.from_pretrained(base_model, "./lora/medical")

    return firefighter_model, police_model, medical_model


if __name__ == "__main__":
    load_expert_adapters()
