"""
Extracted from LLM Training Methodology.
Auto-generated by extract_code_from_methodology.py

`model` is a PeftModel already loaded with multiple named adapters (see
example_lora_adapter_loading.py) -- swapping which adapter is active lets
one loaded base model serve multiple experts without reloading weights.
"""


def swap_to_expert(model, adapter_name):
    """Switch a multi-adapter PeftModel to a different expert's adapter."""
    model.set_adapter(adapter_name)
    return model


if __name__ == "__main__":
    # swap_to_expert(model, "firefighter")  # Switch to firefighter expertise
    # swap_to_expert(model, "police")       # Switch to police expertise
    print(__doc__)
