"""
Extracted from LLM Training Methodology.
Auto-generated by extract_code_from_methodology.py

Shows one loaded model backing multiple expert agents via different system
prompts, instead of one fine-tuned model per agent. Continuation of
example_lmstudio_expert_agent.py -- `client` is the LLM client created there.
"""


def main(client):
    from agents.expert_agent import ExpertAgent

    firefighter_prompt = "You are Pyragos Ioanna Michaelidou, fire commander..."
    police_prompt = "You are Taxiarchos Nikos Konstantinou, police commander..."

    firefighter = ExpertAgent(llm_client=client, system_prompt=firefighter_prompt)
    police = ExpertAgent(llm_client=client, system_prompt=police_prompt)

    return firefighter, police


if __name__ == "__main__":
    from llm_integration.lmstudio_client import LMStudioClient

    demo_client = LMStudioClient(base_url="http://localhost:1234/v1", model_name="firefighter-llama3.1-8b")
    main(demo_client)
