"""
Extracted from LLM Training Methodology.
Auto-generated by extract_code_from_methodology.py

Method to add to the real agents/expert_agent.py::ExpertAgent class in the
main CrisisMAS project (not a standalone tool). Wrapped in a small class
here purely so it has somewhere to be imported/tested from in isolation.
"""

from device_utils import get_device


def _load_fine_tuned_model(self, model_path):
    """Load fine-tuned domain-specific model."""
    import torch
    from transformers import AutoModelForCausalLM, AutoTokenizer
    from peft import PeftModel

    tokenizer = AutoTokenizer.from_pretrained("meta-llama/Meta-Llama-3.1-8B-Instruct")

    # load_in_8bit (bitsandbytes) is CUDA-only -- on Apple Silicon/CPU, load
    # in fp16 instead (bf16 isn't supported on MPS; see APPLE_SILICON_GUIDE.md).
    device = get_device()
    if device == "cuda":
        base_model = AutoModelForCausalLM.from_pretrained(
            "meta-llama/Meta-Llama-3.1-8B-Instruct",
            load_in_8bit=True,
            device_map="auto"
        )
    else:
        base_model = AutoModelForCausalLM.from_pretrained(
            "meta-llama/Meta-Llama-3.1-8B-Instruct",
            torch_dtype=torch.float16,
        ).to(device)
    model = PeftModel.from_pretrained(base_model, model_path)

    return model, tokenizer


class _ExpertAgentFineTunedModelMixin:
    """Mix this (or just copy the method above) into ExpertAgent."""
    _load_fine_tuned_model = _load_fine_tuned_model
