"""
Extracted from LLM Training Methodology.
Auto-generated by extract_code_from_methodology.py
"""

# agents/expert_agent.py (add new method)

def _load_fine_tuned_model(self, model_path):
    """Load fine-tuned domain-specific model."""
    from transformers import AutoModelForCausalLM, AutoTokenizer
    from peft import PeftModel

    tokenizer = AutoTokenizer.from_pretrained("meta-llama/Meta-Llama-3.1-8B-Instruct")
    base_model = AutoModelForCausalLM.from_pretrained(
        "meta-llama/Meta-Llama-3.1-8B-Instruct",
        load_in_8bit=True,
        device_map="auto"
    )
    model = PeftModel.from_pretrained(base_model, model_path)

    return model, tokenizer
