"""
Extracted from LLM Training Methodology.
Auto-generated by extract_code_from_methodology.py
"""

# Swap adapters dynamically
from peft import set_peft_model_state_dict

model.set_adapter("firefighter")  # Switch to firefighter expertise
model.set_adapter("police")       # Switch to police expertise
