"""
Extracted from LLM Training Methodology.
Auto-generated by extract_code_from_methodology.py
"""

# Canary rollout schedule
CANARY_SCHEDULE = [
    {"date": "2025-11-13", "model_b_weight": 0.01},  # Day 1: 1%
    {"date": "2025-11-15", "model_b_weight": 0.05},  # Day 3: 5%
    {"date": "2025-11-18", "model_b_weight": 0.10},  # Day 6: 10%
    {"date": "2025-11-22", "model_b_weight": 0.25},  # Day 10: 25%
    {"date": "2025-11-27", "model_b_weight": 0.50},  # Day 15: 50%
    {"date": "2025-12-04", "model_b_weight": 1.00},  # Day 22: 100%
]

def get_canary_weight():
    """Get current traffic weight for Model B based on schedule."""
    from datetime import date

    today = str(date.today())

    for schedule in reversed(CANARY_SCHEDULE):
        if today >= schedule["date"]:
            return schedule["model_b_weight"]

    return 0.0  # No canary yet

# In your server
AB_TEST_CONFIG["model_b_weight"] = get_canary_weight()
AB_TEST_CONFIG["model_a_weight"] = 1.0 - get_canary_weight()
