"""
Extracted from LLM Training Methodology.
Auto-generated by extract_code_from_methodology.py
"""

import os
from functools import wraps

from flask import request, jsonify


def is_valid_key(api_key):
    """Check an API key against configured valid keys.

    Placeholder: checks against the VALID_API_KEYS env var (comma-separated).
    A real deployment should check against a secrets store / database
    instead of an env var.
    """
    valid_keys = os.environ.get("VALID_API_KEYS", "").split(",")
    return api_key in valid_keys and api_key != ""


def require_api_key(f):
    @wraps(f)
    def decorated_function(*args, **kwargs):
        api_key = request.headers.get('Authorization')
        if not api_key or not is_valid_key(api_key):
            return jsonify({"error": "Unauthorized"}), 401
        return f(*args, **kwargs)
    return decorated_function


def register_routes(app, model):
    """Register the API-key-protected chat route on an existing Flask app."""

    @app.route("/v1/chat/completions", methods=["POST"])
    @require_api_key
    def chat():
        data = request.json
        response = model.generate(data["messages"])
        return jsonify({"choices": [{"message": {"content": response}}]})

    return app


if __name__ == "__main__":
    from flask import Flask

    os.environ.setdefault("VALID_API_KEYS", "demo-key")

    class MockModel:
        def generate(self, messages):
            return "mock response"

    demo_app = Flask(__name__)
    register_routes(demo_app, MockModel())

    client = demo_app.test_client()
    r = client.post(
        "/v1/chat/completions",
        json={"messages": [{"role": "user", "content": "hi"}]},
        headers={"Authorization": "demo-key"},
    )
    print(r.status_code, r.get_json())
