"""
Extracted from LLM Training Methodology.
Auto-generated by extract_code_from_methodology.py
"""

def rollback_to_model_a():
    """Immediately rollback to Model A."""

    print("⚠️ ROLLING BACK TO MODEL A")

    # Set traffic to 100% Model A
    AB_TEST_CONFIG["model_a_weight"] = 1.0
    AB_TEST_CONFIG["model_b_weight"] = 0.0
    AB_TEST_CONFIG["enabled"] = False

    # Send alerts
    send_alert("Model B rolled back to Model A")

    # Log rollback
    with open("rollback_log.txt", "a") as f:
        f.write(f"{time.time()}: Rolled back to Model A\n")

# Manual rollback via API
@app.route("/rollback", methods=["POST"])
def rollback():
    rollback_to_model_a()
    return jsonify({"status": "rolled back to Model A"})
