"""
Extracted from LLM Training Methodology.
Auto-generated by extract_code_from_methodology.py
"""

import time

from alerts import send_alert
from ab_testing_server import AB_TEST_CONFIG


def rollback_to_model_a(ab_test_config=AB_TEST_CONFIG):
    """Immediately rollback to Model A."""

    print("⚠️ ROLLING BACK TO MODEL A")

    # Set traffic to 100% Model A
    ab_test_config["model_a_weight"] = 1.0
    ab_test_config["model_b_weight"] = 0.0
    ab_test_config["enabled"] = False

    # Send alerts
    send_alert("Model B rolled back to Model A", severity="critical")

    # Log rollback
    with open("rollback_log.txt", "a") as f:
        f.write(f"{time.time()}: Rolled back to Model A\n")


def register_routes(app):
    """Register the manual rollback route on an existing Flask app."""
    from flask import jsonify

    @app.route("/rollback", methods=["POST"])
    def rollback():
        rollback_to_model_a()
        return jsonify({"status": "rolled back to Model A"})

    return app
