"""
Extracted from LLM Training Methodology.
Auto-generated by extract_code_from_methodology.py
"""

import logging
import time


def track_inference_time(func):
    def wrapper(*args, **kwargs):
        start = time.time()
        result = func(*args, **kwargs)
        duration = time.time() - start
        logging.info(f"Inference time: {duration:.2f}s")
        return result
    return wrapper


@track_inference_time
def generate_response(model, data):
    return model.generate(data)


if __name__ == "__main__":
    logging.basicConfig(level=logging.INFO)

    class MockModel:
        def generate(self, data):
            return f"response to: {data}"

    print(generate_response(MockModel(), "test input"))
