"""
Extracted from LLM Training Methodology.
Auto-generated by extract_code_from_methodology.py
"""

import re

# Basic heuristic patterns -- not a substitute for a real sanitizer/WAF, but
# catches the crudest injection attempts against a downstream store.
_SQL_INJECTION_PATTERN = re.compile(
    r"(--|;|/\*|\*/|\bunion\b.*\bselect\b|\bdrop\b\s+\btable\b|\bor\b\s+1\s*=\s*1)",
    re.IGNORECASE,
)


def contains_sql_injection(text):
    """Heuristic SQL-injection pattern check. Replace with a real
    sanitizer/parameterized-query discipline for anything that touches a
    database -- this is a best-effort input-validation heuristic only."""
    return bool(_SQL_INJECTION_PATTERN.search(text))


def validate_input(messages, tokenizer, max_messages=20, max_tokens=4000):
    # Check message length
    if len(messages) > max_messages:
        raise ValueError("Too many messages")

    # Check token count
    total_tokens = sum(len(tokenizer.encode(m["content"])) for m in messages)
    if total_tokens > max_tokens:
        raise ValueError("Input too long")

    # Check for malicious content (optional)
    for message in messages:
        if contains_sql_injection(message["content"]):
            raise ValueError("Invalid input detected")
