"""
Extracted from LLM Training Methodology.
Auto-generated by extract_code_from_methodology.py
"""

def validate_input(messages):
    # Check message length
    if len(messages) > 20:
        raise ValueError("Too many messages")

    # Check token count
    total_tokens = sum(len(tokenizer.encode(m["content"])) for m in messages)
    if total_tokens > 4000:
        raise ValueError("Input too long")

    # Check for malicious content (optional)
    for message in messages:
        if contains_sql_injection(message["content"]):
            raise ValueError("Invalid input detected")
