"""
Extracted from LLM Training Methodology.
Auto-generated by extract_code_from_methodology.py
"""

from pingouin import intraclass_corr
import pandas as pd

def calculate_icc(ratings_df):
    """
    Calculate ICC for continuous ratings.

    Args:
        ratings_df: DataFrame with columns ['Example', 'Expert', 'Rating']

    Returns:
        icc: ICC score (0.0-1.0)
    """
    # Calculate ICC(2,1) - two-way random effects, single rater
    icc_result = intraclass_corr(
        data=ratings_df,
        targets='Example',  # What's being rated
        raters='Expert',    # Who's rating
        ratings='Rating',   # The rating value
        nan_policy='omit'
    )

    # Get ICC(2,1) value (most commonly used)
    icc_value = icc_result[icc_result['Type'] == 'ICC2']['ICC'].values[0]

    print(f"ICC(2,1): {icc_value:.3f}")
    print(f"Interpretation: {interpret_icc(icc_value)}")

    return icc_value

def interpret_icc(icc):
    """Interpret ICC score."""
    if icc < 0.50:
        return "Poor reliability"
    elif icc < 0.75:
        return "Moderate reliability"
    elif icc < 0.90:
        return "Good reliability"
    else:
        return "Excellent reliability"

# Example usage
data = {
    'Example': ['EX1', 'EX1', 'EX1', 'EX2', 'EX2', 'EX2', 'EX3', 'EX3', 'EX3'],
    'Expert':  ['A',   'B',   'C',   'A',   'B',   'C',   'A',   'B',   'C'],
    'Rating':  [0.85,  0.90,  0.80,  0.70,  0.75,  0.72,  0.95,  0.92,  0.94]
}
df = pd.DataFrame(data)

icc = calculate_icc(df)

# Target: ICC > 0.75 (good reliability)
