"""
Extracted from LLM Training Methodology.
Auto-generated by extract_code_from_methodology.py
"""

from statsmodels.stats.inter_rater import fleiss_kappa

def calculate_fleiss_kappa(ratings_matrix):
    """
    Calculate Fleiss' Kappa for 3+ experts.

    Args:
        ratings_matrix: 2D array where rows = examples, columns = experts
        Example:
          [[5, 5, 4],  # Example 1: Expert A=5, B=5, C=4
           [4, 4, 5],  # Example 2: Expert A=4, B=4, C=5
           [3, 3, 3]]  # Example 3: All agree = 3

    Returns:
        kappa: Fleiss' Kappa score
    """
    # Convert ratings to categorical counts
    # (Required format for statsmodels)
    from collections import Counter

    num_examples = len(ratings_matrix)
    categories = [1, 2, 3, 4, 5]  # Rating scale

    # Count category occurrences per example
    table = []
    for example_ratings in ratings_matrix:
        counts = Counter(example_ratings)
        row = [counts.get(cat, 0) for cat in categories]
        table.append(row)

    # Calculate Fleiss' Kappa
    kappa = fleiss_kappa(table, method='fleiss')

    print(f"Fleiss' Kappa (n={len(ratings_matrix[0])} raters): {kappa:.3f}")
    print(f"Interpretation: {interpret_kappa(kappa)}")

    return kappa

# Example: 3 experts rate 5 examples
ratings = [
    [5, 5, 4],  # Example 1
    [4, 4, 5],  # Example 2
    [3, 3, 3],  # Example 3 (perfect agreement)
    [5, 4, 5],  # Example 4
    [2, 3, 2]   # Example 5
]

kappa = calculate_fleiss_kappa(ratings)
