"""
Extracted from LLM Training Methodology.
Auto-generated by extract_code_from_methodology.py
"""

# tools/export_from_label_studio.py

import json

def convert_label_studio_to_training(export_file, output_file):
    """Convert Label Studio export to training format."""

    with open(export_file, 'r') as f:
        annotations = json.load(f)

    training_data = []

    for item in annotations:
        # Extract annotations
        question = item['data']['question']
        answer = item['annotations'][0]['result'][0]['value']['text'][0]
        quality = item['annotations'][0]['result'][1]['value']['rating']
        category = item['annotations'][0]['result'][2]['value']['choices']

        training_data.append({
            "instruction": question,
            "output": answer,
            "metadata": {
                "quality": quality,
                "category": category,
                "annotator": item['annotations'][0]['completed_by']
            }
        })

    with open(output_file, 'w') as f:
        json.dump(training_data, f, indent=2, ensure_ascii=False)

# Usage
convert_label_studio_to_training(
    "label_studio_export.json",
    "training_data.json"
)
