"""
Extracted from LLM Training Methodology.
Auto-generated by extract_code_from_methodology.py
"""

# Load ratings
import pandas as pd

ratings = pd.read_csv('expert_ratings.csv')

# Calculate Cohen's Kappa (Expert A vs B)
kappa_ab = cohen_kappa_score(
    ratings['expert_a_quality'],
    ratings['expert_b_quality']
)

kappa_ac = cohen_kappa_score(
    ratings['expert_a_quality'],
    ratings['expert_c_quality']
)

kappa_bc = cohen_kappa_score(
    ratings['expert_b_quality'],
    ratings['expert_c_quality']
)

print(f"Pairwise Agreement:")
print(f"  Expert A vs B: κ = {kappa_ab:.3f}")
print(f"  Expert A vs C: κ = {kappa_ac:.3f}")
print(f"  Expert B vs C: κ = {kappa_bc:.3f}")
print(f"  Average: κ = {np.mean([kappa_ab, kappa_ac, kappa_bc]):.3f}")

# Calculate Fleiss' Kappa (all 3 experts)
ratings_matrix = ratings[['expert_a_quality', 'expert_b_quality', 'expert_c_quality']].values.tolist()
fleiss_k = calculate_fleiss_kappa(ratings_matrix)
