"""
Extracted from LLM Training Methodology.
Auto-generated by extract_code_from_methodology.py
"""

# Python Script Node for Cohen's Kappa
from sklearn.metrics import cohen_kappa_score
import pandas as pd

# Input: ratings from two experts
expert1 = input_table_1['rating'].values
expert2 = input_table_2['rating'].values

kappa = cohen_kappa_score(expert1, expert2)

# Output table
output_table = pd.DataFrame({
    'metric': ['Cohen\'s Kappa'],
    'value': [kappa],
    'interpretation': ['Substantial' if kappa > 0.7 else 'Moderate' if kappa > 0.4 else 'Poor']
})
