"""
Extracted from LLM Training Methodology.
Auto-generated by extract_code_from_methodology.py
"""

def flag_for_review(question, answers, reason):
    """Flag example as disputed for senior expert review."""

    flagged_example = {
        "question": question,
        "disputed_answers": answers,
        "status": "flagged_for_review",
        "reason": reason,
        "flagged_date": datetime.now().isoformat(),
        "assigned_to": "senior_expert_reviewer",
        "priority": "high" if "safety" in reason.lower() else "medium"
    }

    # Save to review queue
    with open('disputed_examples.jsonl', 'a') as f:
        f.write(json.dumps(flagged_example) + '\n')

    print(f"⚠️ Flagged for senior review:")
    print(f"   Reason: {reason}")
    print(f"   Priority: {flagged_example['priority']}")

    return flagged_example

# Example: Safety-critical disagreement
flag_for_review(
    question="What is the IDLH for ammonia?",
    answers=[
        ("300 ppm", 0.9),
        ("500 ppm", 0.8)
    ],
    reason="Safety-critical: Incorrect IDLH could endanger lives"
)
