"""
Extracted from LLM Training Methodology.
Auto-generated by extract_code_from_methodology.py
"""

def resolve_with_context(question, answers):
    """Create context-specific examples when both answers are valid."""

    print("Creating context-specific training examples:")

    examples = []

    # Example 1: Context favors answer A
    examples.append({
        "question": question + " (limited resources, high wind)",
        "answer": answers[0],  # Evacuate
        "reasoning": "With limited resources and dangerous conditions, evacuation is the only safe option.",
        "context": "resource_constrained"
    })

    # Example 2: Context favors answer B
    examples.append({
        "question": question + " (sufficient resources, moderate conditions)",
        "answer": answers[1],  # Defend
        "reasoning": "With adequate resources and manageable conditions, structural defense is viable.",
        "context": "resource_adequate"
    })

    print(f"✅ Created {len(examples)} context-specific examples")
    return examples

# Example: Tactical disagreement
examples = resolve_with_context(
    question="Should we defend the structure or evacuate?",
    answers=[
        "Evacuate immediately - insufficient resources",
        "Defend structure - we have the capability"
    ]
)

for ex in examples:
    print(f"\nQ: {ex['question']}")
    print(f"A: {ex['answer']}")
    print(f"Context: {ex['context']}")
