"""
Extracted from LLM Training Methodology.
Auto-generated by extract_code_from_methodology.py
"""

def resolve_with_confidence_weighting(answers_with_confidence):
    """Weight answers by expert confidence."""

    # answers_with_confidence = [(answer_a, 0.9), (answer_b, 0.5), (answer_c, 0.8)]

    # Group by answer text
    from collections import defaultdict
    answer_scores = defaultdict(float)

    for answer, confidence in answers_with_confidence:
        answer_scores[answer] += confidence

    # Select answer with highest weighted confidence
    best_answer = max(answer_scores.items(), key=lambda x: x[1])

    avg_confidence = best_answer[1] / len(answers_with_confidence)

    print(f"Confidence-weighted resolution:")
    print(f"  Selected: {best_answer[0]}")
    print(f"  Weighted confidence: {avg_confidence:.2f}")

    return {
        "answer": best_answer[0],
        "confidence": avg_confidence,
        "metadata": {
            "resolution_method": "confidence_weighting",
            "all_answers": dict(answer_scores)
        }
    }

# Example
resolve_with_confidence_weighting([
    ("Evacuate", 0.95),  # Expert A: very confident
    ("Defend", 0.50),    # Expert B: uncertain
    ("Evacuate", 0.80)   # Expert C: confident
])
# Result: "Evacuate" with weighted confidence 0.75
