"""
Extracted from LLM Training Methodology.
Auto-generated by extract_code_from_methodology.py
"""

def resolve_with_tiebreaker(question, answer_a, answer_b, confidence_a, confidence_b):
    """Resolve disagreement with third expert tie-breaker."""

    print(f"Disagreement detected:")
    print(f"  Expert A ({confidence_a:.0%} confident): {answer_a}")
    print(f"  Expert B ({confidence_b:.0%} confident): {answer_b}")

    # Consult third expert
    answer_c = get_expert_c_answer(question)

    # Majority vote
    answers = [answer_a, answer_b, answer_c]
    from collections import Counter
    vote_counts = Counter(answers)
    majority_answer = vote_counts.most_common(1)[0][0]

    agreement_level = vote_counts[majority_answer] / 3

    if agreement_level >= 0.66:  # 2/3 agree
        print(f"✅ Resolved: {majority_answer} (2/3 experts agree)")
        return {
            "answer": majority_answer,
            "confidence": 0.8,  # High confidence (majority)
            "metadata": {
                "resolution_method": "tie-breaker",
                "votes": dict(vote_counts),
                "disputed": True
            }
        }
    else:
        print("⚠️ No consensus (all 3 disagree)")
        return resolve_with_context(question, [answer_a, answer_b, answer_c])

# Example
resolve_with_tiebreaker(
    question="Evacuate or defend structure fire with limited resources?",
    answer_a="Evacuate - insufficient resources for safe defense",
    answer_b="Defend - structure can be saved",
    confidence_a=0.9,
    confidence_b=0.7
)
