"""
Extracted from LLM Training Methodology.
Auto-generated by extract_code_from_methodology.py
"""

import random

def select_sample_for_multi_rating(dataset_path, sample_size=50, seed=42):
    """Select random sample for multiple experts to rate."""

    random.seed(seed)

    with open(dataset_path, 'r') as f:
        all_examples = [line.strip() for line in f if line.strip()]

    # Random sample
    sample = random.sample(all_examples, min(sample_size, len(all_examples)))

    # Save sample for expert review
    with open('multi_rating_sample.jsonl', 'w') as f:
        for example in sample:
            f.write(example + '\n')

    print(f"✅ Selected {len(sample)} examples for multi-rating")
    print("Send 'multi_rating_sample.jsonl' to 2-3 experts")

    return sample
