"""
Extracted from LLM Training Methodology.
Auto-generated by extract_code_from_methodology.py
"""

# tools/setup_argilla.py

import argilla as rg

# Initialize client
rg.init(api_url="http://localhost:6900", api_key="argilla.apikey")

# Create dataset for annotation
dataset = rg.DatasetForTextClassification(
    name="emergency_response_qa",
    description="Expert Q&A for emergency response training"
)

# Add records
records = []
for item in raw_questions:
    records.append(
        rg.TextClassificationRecord(
            text=f"Q: {item['question']}\nA: ",
            metadata={"expert_id": item["expert"], "date": item["date"]},
            annotation=[],  # To be filled by annotators
        )
    )

rg.log(records, name="emergency_response_qa")
