"""
Extracted from LLM Training Methodology.
Auto-generated by extract_code_from_methodology.py
"""

# tools/track_collection.py

import wandb
import json

# Initialize W&B project
wandb.init(project="crisis-mas-llm-training", name="data-collection")

# Load training data
with open("training_data.json", "r") as f:
    data = json.load(f)

# Log metrics
wandb.log({
    "total_examples": len(data),
    "avg_question_length": sum(len(d["question"]) for d in data) / len(data),
    "avg_answer_length": sum(len(d["answer"]) for d in data) / len(data),
})

# Log data distribution
categories = {}
for item in data:
    cat = item["metadata"]["category"]
    categories[cat] = categories.get(cat, 0) + 1

wandb.log({"category_distribution": wandb.Histogram(list(categories.values()))})

# Log quality distribution
qualities = [item["metadata"]["quality"] for item in data]
wandb.log({"quality_distribution": wandb.Histogram(qualities)})

# Create table of examples
table = wandb.Table(columns=["question", "answer", "quality", "category"])
for item in data[:100]:  # First 100 examples
    table.add_data(
        item["question"][:100],
        item["answer"][:100],
        item["metadata"]["quality"],
        item["metadata"]["category"]
    )
wandb.log({"examples": table})

wandb.finish()
