"""
Extracted from LLM Training Methodology.
Auto-generated by extract_code_from_methodology.py
"""

   # model_metadata.json
   {
       "model_version": "2.1.0",
       "training_dataset": {
           "version": "2.1.0",
           "hash": "a3f5b9c...",
           "path": "datasets/v2.1.0/firefighter_train.jsonl"
       }
   }
