"""
Extracted from LLM Training Methodology.
Auto-generated by extract_code_from_methodology.py

KNIME "Python Script Node" snippet. `input_table_1`, `input_table_2`, and
`output_table` are injected/extracted automatically by KNIME's Python Script
node -- this cannot run as a plain Python script outside KNIME. The
`__main__` block below substitutes plain DataFrames so the core logic can
still be exercised and tested independently of KNIME.
"""

from sklearn.metrics import cohen_kappa_score
import pandas as pd


def compute_cohens_kappa_table(input_table_1, input_table_2):
    expert1 = input_table_1['rating'].values
    expert2 = input_table_2['rating'].values

    kappa = cohen_kappa_score(expert1, expert2)

    return pd.DataFrame({
        'metric': ["Cohen's Kappa"],
        'value': [kappa],
        'interpretation': ['Substantial' if kappa > 0.7 else 'Moderate' if kappa > 0.4 else 'Poor'],
    })


if __name__ == "__main__":
    # Standalone demo (in KNIME, input_table_1/input_table_2 would already
    # be provided by the upstream nodes -- paste the function body below
    # directly into the node instead of importing this file):
    #   output_table = compute_cohens_kappa_table(input_table_1, input_table_2)
    demo_input_table_1 = pd.DataFrame({'rating': [5, 4, 5, 3, 4]})
    demo_input_table_2 = pd.DataFrame({'rating': [5, 4, 4, 3, 5]})
    print(compute_cohens_kappa_table(demo_input_table_1, demo_input_table_2))
