"""
Extracted from LLM Training Methodology.
Auto-generated by extract_code_from_methodology.py
"""

from resolve_with_context import resolve_with_context


def resolve_with_tiebreaker(question, answer_a, answer_b, confidence_a, confidence_b,
                             get_third_expert_answer):
    """Resolve disagreement with third expert tie-breaker.

    Args:
        get_third_expert_answer: callable(question) -> str. Consulting a real
            third expert is inherently human-in-the-loop (or a call into your
            own expert-consultation/annotation system) -- there is no generic
            default for it, so it must be supplied by the caller.
    """

    print(f"Disagreement detected:")
    print(f"  Expert A ({confidence_a:.0%} confident): {answer_a}")
    print(f"  Expert B ({confidence_b:.0%} confident): {answer_b}")

    # Consult third expert
    answer_c = get_third_expert_answer(question)

    # Majority vote
    answers = [answer_a, answer_b, answer_c]
    from collections import Counter
    vote_counts = Counter(answers)
    majority_answer = vote_counts.most_common(1)[0][0]

    agreement_level = vote_counts[majority_answer] / 3

    if agreement_level >= 0.66:  # 2/3 agree
        print(f"✅ Resolved: {majority_answer} (2/3 experts agree)")
        return {
            "answer": majority_answer,
            "confidence": 0.8,  # High confidence (majority)
            "metadata": {
                "resolution_method": "tie-breaker",
                "votes": dict(vote_counts),
                "disputed": True
            }
        }
    else:
        print("⚠️ No consensus (all 3 disagree)")
        return resolve_with_context(question, [answer_a, answer_b, answer_c])


if __name__ == "__main__":
    resolve_with_tiebreaker(
        question="Evacuate or defend structure fire with limited resources?",
        answer_a="Evacuate - insufficient resources for safe defense",
        answer_b="Defend - structure can be saved",
        confidence_a=0.9,
        confidence_b=0.7,
        # Mock third-expert callback for the demo -- in production this
        # would query a real expert or an annotation queue.
        get_third_expert_answer=lambda q: "Evacuate - insufficient resources for safe defense",
    )
