"""
Extracted from LLM Training Methodology.
Auto-generated by extract_code_from_methodology.py

Requires a running Argilla server (see https://docs.argilla.io) --
this cannot be exercised without one, by design.
"""

import argilla as rg


def push_questions_to_argilla(raw_questions, api_url="http://localhost:6900",
                               api_key="argilla.apikey"):
    """Create an Argilla annotation dataset and push raw Q&A records to it."""

    rg.init(api_url=api_url, api_key=api_key)

    dataset = rg.DatasetForTextClassification(
        name="emergency_response_qa",
        description="Expert Q&A for emergency response training"
    )

    records = []
    for item in raw_questions:
        records.append(
            rg.TextClassificationRecord(
                text=f"Q: {item['question']}\nA: ",
                metadata={"expert_id": item["expert"], "date": item["date"]},
                annotation=[],  # To be filled by annotators
            )
        )

    rg.log(records, name="emergency_response_qa")
    return dataset


if __name__ == "__main__":
    raw_questions = [
        {"question": "What is the IDLH for ammonia?", "expert": "EXP-042", "date": "2024-10-15"},
        {"question": "Evacuate or defend structure fire with limited resources?", "expert": "EXP-017", "date": "2024-10-16"},
    ]
    push_questions_to_argilla(raw_questions)
