"""
Extracted from LLM Training Methodology.
Auto-generated by extract_code_from_methodology.py

Requires a Weights & Biases account/login (wandb.init will prompt otherwise).
"""

import json

import wandb


def track_collection(data_path="training_data.json", project="crisis-mas-llm-training"):
    """Log data-collection quality metrics to W&B.

    Expects records shaped like export_from_label_studio.py's output:
    {"instruction": ..., "output": ..., "metadata": {"quality": ..., "category": ...}}.
    """

    wandb.init(project=project, name="data-collection")

    with open(data_path, "r") as f:
        data = json.load(f)

    wandb.log({
        "total_examples": len(data),
        "avg_question_length": sum(len(d["instruction"]) for d in data) / len(data),
        "avg_answer_length": sum(len(d["output"]) for d in data) / len(data),
    })

    # Log data distribution
    categories = {}
    for item in data:
        cat = item["metadata"]["category"]
        categories[cat] = categories.get(cat, 0) + 1

    wandb.log({"category_distribution": wandb.Histogram(list(categories.values()))})

    # Log quality distribution
    qualities = [item["metadata"]["quality"] for item in data]
    wandb.log({"quality_distribution": wandb.Histogram(qualities)})

    # Create table of examples
    table = wandb.Table(columns=["question", "answer", "quality", "category"])
    for item in data[:100]:  # First 100 examples
        table.add_data(
            item["instruction"][:100],
            item["output"][:100],
            item["metadata"]["quality"],
            item["metadata"]["category"],
        )
    wandb.log({"examples": table})

    wandb.finish()


if __name__ == "__main__":
    track_collection()
