"""
Extracted from LLM Training Methodology.
Auto-generated by extract_code_from_methodology.py
"""

# tools/ab_test_dashboard.py

from flask import Flask, render_template
import json

app = Flask(__name__)

@app.route("/dashboard")
def dashboard():
    """Real-time A/B testing dashboard."""

    # Load metrics
    with open("ab_test_logs.jsonl", "r") as f:
        logs = [json.loads(line) for line in f]

    model_a_logs = [log for log in logs if log["model"] == "model_a"]
    model_b_logs = [log for log in logs if log["model"] == "model_b"]

    # Calculate metrics
    metrics = {
        "model_a": {
            "requests": len(model_a_logs),
            "avg_latency": sum(log["latency_ms"] for log in model_a_logs) / len(model_a_logs),
            "error_rate": sum(1 for log in model_a_logs if log["error"]) / len(model_a_logs),
        },
        "model_b": {
            "requests": len(model_b_logs),
            "avg_latency": sum(log["latency_ms"] for log in model_b_logs) / len(model_b_logs),
            "error_rate": sum(1 for log in model_b_logs if log["error"]) / len(model_b_logs),
        }
    }

    return render_template("ab_test_dashboard.html", metrics=metrics)

if __name__ == "__main__":
    app.run(port=5000)
