"""
Extracted from LLM Training Methodology.
Auto-generated by extract_code_from_methodology.py
"""

class AlertManager:
    """Prevent alert fatigue with smart grouping and throttling."""

    def __init__(self):
        self.alert_history = {}
        self.throttle_window = 3600  # 1 hour

    def should_send_alert(self, alert_type: str) -> bool:
        """Throttle repeated alerts."""

        last_alert_time = self.alert_history.get(alert_type, 0)
        current_time = time.time()

        if current_time - last_alert_time < self.throttle_window:
            return False  # Alert sent recently, throttle

        self.alert_history[alert_type] = current_time
        return True

    def group_alerts(self, alerts: List[Dict]) -> List[Dict]:
        """Group similar alerts together."""

        grouped = {}

        for alert in alerts:
            key = (alert["severity"], alert["type"])

            if key not in grouped:
                grouped[key] = {
                    "severity": alert["severity"],
                    "type": alert["type"],
                    "count": 0,
                    "first_occurrence": alert["timestamp"],
                    "messages": []
                }

            grouped[key]["count"] += 1
            grouped[key]["messages"].append(alert["message"])

        # Format grouped alerts
        result = []
        for (severity, alert_type), data in grouped.items():
            if data["count"] > 1:
                message = f"{data['count']} {alert_type} alerts (first: {data['messages'][0]})"
            else:
                message = data["messages"][0]

            result.append({
                "severity": severity,
                "type": alert_type,
                "message": message,
                "count": data["count"]
            })

        return result
