"""
Extracted from LLM Training Methodology.
Auto-generated by extract_code_from_methodology.py
"""

import logging

logging.basicConfig(
    filename='llm_requests.log',
    level=logging.INFO,
    format='%(asctime)s - %(message)s'
)

@app.route("/v1/chat/completions", methods=["POST"])
def chat():
    data = request.json
    logging.info(f"Request: {data['messages']}")

    response = generate_response(data)

    logging.info(f"Response: {response}")
    return response
