"""
Extracted from LLM Training Methodology.
Auto-generated by extract_code_from_methodology.py
"""

class ConceptDriftDetector:
    """Detect when model's learned concepts become outdated."""

    def __init__(self):
        self.reference_set = self._load_reference_set()
        self.drift_threshold = 0.15  # Alert if accuracy drops >15%

    def _load_reference_set(self):
        """Load gold-standard test set for drift detection."""
        # This is your evaluation benchmark from training
        with open("reference_test_set.json", "r") as f:
            return json.load(f)

    def check_drift_monthly(self, model):
        """Run drift detection monthly on reference set."""

        print("Running concept drift detection...")

        correct = 0
        total = len(self.reference_set)

        for item in self.reference_set:
            response = model.generate(item["question"])

            # Check if answer is correct (fuzzy match)
            if self._is_correct(response, item["correct_answer"]):
                correct += 1

        current_accuracy = correct / total
        baseline_accuracy = 0.85  # Your accuracy at deployment time

        accuracy_drop = baseline_accuracy - current_accuracy

        print(f"Reference Set Accuracy: {current_accuracy:.1%}")
        print(f"Baseline Accuracy: {baseline_accuracy:.1%}")
        print(f"Accuracy Drop: {accuracy_drop:+.1%}")

        if accuracy_drop > self.drift_threshold:
            self._send_drift_alert(
                current_accuracy=current_accuracy,
                baseline_accuracy=baseline_accuracy,
                accuracy_drop=accuracy_drop
            )

            return True  # Drift detected

        return False  # No drift

    def _is_correct(self, response: str, correct_answer: str) -> bool:
        """Check if response matches correct answer (fuzzy)."""
        from difflib import SequenceMatcher

        similarity = SequenceMatcher(None, response.lower(), correct_answer.lower()).ratio()
        return similarity > 0.8

    def _send_drift_alert(self, current_accuracy, baseline_accuracy, accuracy_drop):
        """Alert that concept drift detected."""
        alert = {
            "type": "concept_drift",
            "severity": "critical",
            "message": f"Model accuracy dropped from {baseline_accuracy:.1%} to {current_accuracy:.1%}",
            "recommendation": "Retrain model with updated data",
            "timestamp": time.time()
        }

        with open("drift_alerts.jsonl", "a") as f:
            f.write(json.dumps(alert) + "\n")

        # Send to monitoring
        send_to_pagerduty(alert)

# Schedule monthly drift detection
import schedule

drift_detector = ConceptDriftDetector()

def run_drift_detection():
    drift_detected = drift_detector.check_drift_monthly(model)
    if drift_detected:
        print("⚠️ CONCEPT DRIFT DETECTED - Retraining recommended")

# Run on first day of each month
schedule.every().month.at("00:00").do(run_drift_detection)
