"""
Extracted from LLM Training Methodology.
Auto-generated by extract_code_from_methodology.py
"""

# Single model, different system prompts
firefighter_prompt = "You are Pyragos Ioanna Michaelidou, fire commander..."
police_prompt = "You are Taxiarchos Nikos Konstantinou, police commander..."

firefighter = ExpertAgent(llm_client=client, system_prompt=firefighter_prompt)
police = ExpertAgent(llm_client=client, system_prompt=police_prompt)
