"""
Extracted from LLM Training Methodology.
Auto-generated by extract_code_from_methodology.py
"""

from llm_integration.lmstudio_client import LMStudioClient

# Point to your deployed model
client = LMStudioClient(
    base_url="http://localhost:1234/v1",  # or vLLM server
    model_name="firefighter-llama3.1-8b"
)

# Use in expert agent
from agents.expert_agent import ExpertAgent

firefighter = ExpertAgent(
    name="Pyragos Ioanna Michaelidou",
    role="Fire Tactical Commander",
    expertise="firefighting",
    llm_client=client
)

assessment = firefighter.assess_scenario(scenario_data)
