"""
Extracted from LLM Training Methodology.
Auto-generated by extract_code_from_methodology.py
"""

from openai import OpenAI

client = OpenAI(
    base_url="http://localhost:8000/v1",
    api_key="dummy"  # vLLM doesn't require real key
)

response = client.chat.completions.create(
    model="firefighter-llama3.1-8b",
    messages=[
        {"role": "system", "content": "You are Pyragos Ioanna Michaelidou..."},
        {"role": "user", "content": "A wildfire is approaching. What do I do?"}
    ],
    temperature=0.7,
    max_tokens=512
)

print(response.choices[0].message.content)
