"""
Extracted from LLM Training Methodology.
Auto-generated by extract_code_from_methodology.py
"""

from peft import PeftModel

# Load base model once
base_model = AutoModelForCausalLM.from_pretrained("meta-llama/Meta-Llama-3.1-8B-Instruct")

# Load different LoRA adapters
firefighter_model = PeftModel.from_pretrained(base_model, "./lora/firefighter")
police_model = PeftModel.from_pretrained(base_model, "./lora/police")
medical_model = PeftModel.from_pretrained(base_model, "./lora/medical")
