"""
Extracted from LLM Training Methodology.
Auto-generated by extract_code_from_methodology.py
"""

from functools import wraps

def require_api_key(f):
    @wraps(f)
    def decorated_function(*args, **kwargs):
        api_key = request.headers.get('Authorization')
        if not api_key or not is_valid_key(api_key):
            return jsonify({"error": "Unauthorized"}), 401
        return f(*args, **kwargs)
    return decorated_function

@app.route("/v1/chat/completions", methods=["POST"])
@require_api_key
def chat():
    # ... inference code
