"""
Extracted from LLM Training Methodology.
Auto-generated by extract_code_from_methodology.py
"""

import time

def track_inference_time(func):
    def wrapper(*args, **kwargs):
        start = time.time()
        result = func(*args, **kwargs)
        duration = time.time() - start
        logging.info(f"Inference time: {duration:.2f}s")
        return result
    return wrapper

@track_inference_time
def generate_response(data):
    # ... inference code
